require('./build-outing.cjs');
// Run after changing content data. No external dependencies; works on Node 20+.
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const context = vm.createContext({Date,Intl,URL,URLSearchParams});
for (const name of ['publish-schedule.js','blog-data.js','guide-data.js','comic-data.js','event-data.js']) {
  vm.runInContext(fs.readFileSync(path.join(root,name),'utf8'),context,{timeout:2000});
}
const content = vm.runInContext('({blog:blogPosts,guide:guidePosts,comics:comicData,series:comicSeriesData,events:calendarEvents})',context);
const socialMapFile=path.join(root,'edge/social-images.json');
content.socialImages=fs.existsSync(socialMapFile)?JSON.parse(fs.readFileSync(socialMapFile,'utf8')):{};
const runtime=fs.readFileSync(path.join(root,'edge/sharing-runtime.mjs'),'utf8');
fs.writeFileSync(path.join(root,'_worker.js'),'// Generated by tools/build-sharing.cjs. Do not hand-edit.\nconst CONTENT = '+JSON.stringify(content)+';\n'+runtime);
console.log('Built sharing metadata for',content.blog.length,'blog articles,',content.guide.length,'guides,',content.comics.length,'episodes and',content.series.length,'series.');
